feat(textfield): update component to meet new specifications
natura-cosmeticos/natds-rn pull request #177
Opened 2021-05-25 11:45 UTC by lauralucca

# Description

Please include a summary of the changes and features that were added. Also include which JIRA task is this related to (name and link). List any dependencies that were added or removed for this change.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-05-31 19:47 UTC, arielwb requested changes

2021-05-31 19:47 UTC, arielwb commented on src/common/themeSelectors/sizes/sizes.ts
> +export const getBorderRadiusMedium = (theme: Theme) => getRadiusBySize(theme, 'medium');
faltam os testes das novas funções desse arquivo

2021-05-31 19:47 UTC, arielwb commented on src/components/InputFeedbackContainer/InputFeedbackContainer.tsx
> +const getBoxColor = ({
refatorar para diminuir a complexidade

2021-05-31 19:47 UTC, arielwb commented on src/components/InputFeedbackContainer/InputFeedbackContainer.tsx
> +const getTextElementsColor = ({
refatorar pra diminuir a complexidade

2021-05-31 19:47 UTC, arielwb commented on src/components/InputFeedbackContainer/InputFeedbackContainer.tsx
> +const HelperText = ({ children, color, feedback }) => {
separa os sub componentes e suas funções em arquivos pra facilitar a leitura.
aqui temos logica e tipos da label, helper text e input todos juntos

2021-05-31 19:47 UTC, arielwb commented on src/components/InputFeedbackContainer/InputFeedbackContainer.tsx
> +    <View style={{ width: '100%' }}>
eu entendo que é chato fazer um styled componente pra cada VIew, mas o resultado final desse componente me pareceu mais dificil de ler do que necessario. Talvez so extraindo o componente do icone já ajude, mas acho que da pra melhorar

2021-05-31 19:47 UTC, arielwb commented on src/components/InputFeedbackContainer/InputFeedbackContainer.tsx
> +      <View style={{
criar styled components pra essas views

2021-05-31 19:47 UTC, arielwb commented on src/components/InputFeedbackContainer/InputFeedbackContainer.tsx
> +            <Icon testID="icon" name={iconName} color={iconColor} size="small" />
o icone do feedback tem ação no click? por ex, a usuaria poderia inserir um icone de olho e querer mostrar o password no click

2021-05-31 19:47 UTC, arielwb commented on src/components/TextField/TextField.tsx
> +  }: TextFieldProps = props;
eu acho mto ruim dar o spread de todas as props assim e ter que repassar todas pro componente de TextInput.
sera que nao enocntramos uma forma melhor de resolver isso?

2021-05-31 19:47 UTC, arielwb commented on src/components/TextField/TextField.tsx
> +        style={{
styled component

2021-05-31 19:47 UTC, arielwb commented on src/components/TextField/TextField.tsx
> +        && <View style={{ paddingRight: getSpacingTiny(theme) }}>
extrair isso em um componente

2021-05-31 19:47 UTC, arielwb commented on src/components/TextField/TextField.tsx
> +        && <TouchableRipple
extrair isso em um componente

2021-06-01 15:14 UTC, lauralucca commented on src/components/InputFeedbackContainer/InputFeedbackContainer.tsx
> +            <Icon testID="icon" name={iconName} color={iconColor} size="small" />
Nesse caso acho que você tá pensando no ícone de ação do TextField. Esse aqui é um íconezinho de indicação que aparece embaixo do campo quando muda a cor (para quem não diferencia vermelho ou verde). É o (𐄂) e o (✓) na imagem abaixo:

![image](https://user-images.githubusercontent.com/30187869/120346541-d6a4a580-c2d1-11eb-9938-71a85a4b566e.png)

Com a refatoração desse componente e separação de tudo vou deixar mais nítido o que representa o quê!

2021-06-02 14:48 UTC, lauralucca commented on src/components/TextField/TextField.types.ts
> +interface ActionImageProps {
Conversei com o Rafa sobre isso, ele respondeu que imaginou a imagem com ação sim, opcional. Eu tinha deduzido isso de ele ter chamado o atributo "Action", mas eu acho que é questionável, se a gente entender como desnecessário. Parece que rola um YAGNI aqui.

2021-06-08 17:40 UTC, lauralucca commented on src/components/TextField/TextField.types.ts
> +interface ActionImageProps {
Removi o ripple e o onPress, para ficar igual as outras stacks. Vamos conversar com Rafa e Lucas sobre a necessidade de incluir isso.

2021-06-09 14:42 UTC, lauralucca commented on src/components/TextField/TextField.tsx
> +  }: TextFieldProps = props;
Testei de várias formas e a maioria deixa possível alterar as props de estilos que queremos evitar. Tenho essas duas sugestões que funcionam: https://github.com/natura-cosmeticos/natds-rn/pull/177/commits/c7801de3cfa89caea8f1d05567a5357a6c5f13ca (nesse commit eu substituí uma pela outra, então você pode ver uma em vermelho a outra em verde. Caso você veja algumas das duas como mais legível ou desejável, é só dar um toque)

Enquanto mexia nisso, fiz rapidinho um teste automatizado para garantir (embora não commitei ele, porque não achei que fazia sentido ter ele na lib) e confirmei que tudo funciona como esperado.

![image](https://user-images.githubusercontent.com/30187869/121375069-d1210e00-c916-11eb-9e8b-a9adb21ca484.png)

Percebi que outra opção seria passar as props que eu não quero permitir, que são menos, porque as que eu defini no componente a usuária não consegue sobrescrever. Mas essa última opção eu achei muito provável de criar confusão e de piorar o autocomplete do ts.

![image](https://user-images.githubusercontent.com/30187869/121374775-91f2bd00-c916-11eb-8a0e-5e07fc97940b.png)

2021-06-09 14:58 UTC, lauralucca commented on package.json
> +  "version": "7.1.0-DSY-2081.4",
Realmente! A lógica anterior era muito complexa e acoplada, então eu precisei remover para desenvolver o atributo Action. Quando a gente conversou sobre os tipos Number e Multiline serem props do React Native, acabei deixando sem o Password também.

Eu prefiro evitar a breaking change, mas também acho que manter isso no componente deixa acoplado o `IconButton` com os ícones de 👁 e a prop de `'secureText'` e isso pode impedir a usuária de usá-las separadas.

@yasminnvaz @arielwb 
Se a gente estiver OK com isso, adiciono agora no componente!

Só para mostrar, também é bem simples de fazer pelo lado da usuária, dá uma olhada:

![image](https://user-images.githubusercontent.com/30187869/121377731-f878da80-c918-11eb-9af5-99527089e106.png)

2021-06-09 15:43 UTC, lauralucca commented on package.json
> +  "version": "7.1.0-DSY-2081.4",
https://natds-rn.natura.design/DSY-2081-textfield/index.html?path=/story/components-textfield--password

2021-06-09 21:20 UTC, arielwb commented on src/components/InputFeedbackContainer/InputFeedbackContainer.tsx
> +  return colors[state || 'default'][element];
LINDOOOOOOOOO! <3

2021-06-09 21:20 UTC, arielwb commented on src/components/InputFeedbackContainer/InputFeedbackHelper.ts
> +}: InputFeedbackProps) => {
aqui eu fiquei com duvidas:
essa função é usada somente pra pegar o estado correto pra usar na função `getElementsColorsByState`, certo?
Se sim, tenho alguns pontos:
- Acho que o retorno no if feedback deveria ser uma string, e nao um boolean
- feedback não existe em `getElementsColorsByState`
- error não existe em `buildInputState`
Acho que tu pode usar o typescript pra garantir que essas duas funções vao seguir alinhadas, dizendo que o tipo do retorno aqui é um `InputStates`. Hoje o retorno dessa função é string | boolean

2021-06-09 21:20 UTC, arielwb commented on src/components/InputFeedbackContainer/InputFeedbackContainer.tsx
> +  return colors[state || 'default'][element];
porem aqui no retorno acho que a gente pode remover o default, pq tu já retorna ele na `buildInputState`.
outra dica pra deixar tudo ainda mais amarradinho: acho que a const colors merece um tipo que garanta que as chaves desse objeto sejam somente do tipo `InputStates`.
Ai se um dia default virar banana, o TS vai te ajudar a saber onde tem que trocar

2021-06-09 22:14 UTC, lauralucca commented on src/components/InputFeedbackContainer/InputFeedbackContainer.tsx
> +  return colors[state || 'default'][element];
Mas o `InputStates` já é um tipo, eu declarei na primeira linha do `./InputFeedbackHelper.ts`
Talvez faz mais sentido declarar aqui?

2021-06-10 12:18 UTC, lauralucca commented on src/components/InputFeedbackContainer/InputFeedbackContainer.tsx
> +  return colors[state || 'default'][element];
AH eu tinha entendido errado. Fiz o tipo e removi o "default", tudo certo!

2021-06-10 12:31 UTC, lauralucca commented on src/components/InputFeedbackContainer/InputFeedbackHelper.ts
> +}: InputFeedbackProps) => {
Coloquei o tipo InputStates no retorno!

Sobre o resto das alterações, já funciona assim! Na verdade o tipo de Feedback não é um boolean, é o union das strings "error" e "success". Por isso que essa função manda "error" e "success" pra `'getElementsColorsByState'`

Eu pensei em colocar mais explicito, tipo:
```
if (feedback === "error") return "error";
if (feedback === "success") return "success";
```
maaaaaas aí é mais um if né. Cansada de ifs. hahaha

2021-06-17 16:15 UTC, yasminnvaz submitted a review, later dismissed

2021-06-21 17:30 UTC, merged