[DSY-827] feat(avatar): add Avatar component, test and stories
natura-cosmeticos/natds-rn pull request #75
Opened 2020-08-21 18:45 UTC by douglasofreitas

DSY-827

# Description

Please include a summary of the changes and features that were added. Also include which JIRA task is this related to (name and link). List any dependencies that were added or removed for this change.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Use Storybook to see Avatar component
- [ ] Change Type, Text value, and Size to see behaviors.  

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2020-08-27 19:47 UTC, douglasofreitas commented on src/components/Avatar/Avatar.test.tsx
> +    expect(queryByTestId('avatar')?.props).toHaveProperty('type', 'anonymous');
o default é o próprio anonymous mesmo, que não precisa de imagem e nem de texto para funcionar

2020-08-27 19:48 UTC, douglasofreitas commented on src/components/Avatar/Avatar.tsx
> +    tiny: '10px',
no DS não tem fontSize em PX só em REM, no momento vamos usar um de => para até termos uma forma de converter do DS ou pegar num formato numérico ou PX

2020-09-01 18:12 UTC, lauralucca commented on src/common/themeSelectors/avatarSizes/avatarSizes.ts
> +import { Theme, checkTheme } from '..';
se fizer sentido pra você, coloca um `/* eslint-disable sort-keys */` no começo desse arquivo pra ordenar os tamanhos numa ordem crescente ou decrescente. acho que vai ficar mais fácil de ler

2020-09-01 18:35 UTC, lauralucca commented on src/components/Avatar/Avatar.stories.tsx
> +const imgSource = 'https://pbs.twimg.com/profile_images/1285932878795333632/Wl95KE_m_400x400.jpg';
Não sei por que, mas a imagem não aparece pra mim. Será alguma coisa no Storybook @arielwb ?
https://natds-rn-feature-avatar.netlify.app/?path=/story/components-avatar--all

2020-09-01 18:39 UTC, lauralucca commented on src/components/Avatar/Avatar.tsx
> +  color?: AvatarColors;
Na UI Doc o componente não recebe cores, né? Acho que pode tirar

2020-09-01 19:43 UTC, lauralucca commented on src/components/Avatar/Avatar.tsx
> +  const firstAndLast = `${firstLetters[0]}${firstLetters[firstLetters.length - 1]}`;
Muito bom! Só que se o componente receber um nome só com 3 caracteres ou mais ele duplica a primeira letra. Acho que podia adicionar uma verificação tipo:
```
const firstAndLast = firstLetters.length > 1
  ? `${firstLetters[0]}${firstLetters[firstLetters.length - 1]}`
  : `${firstLetters[0]}`;
```

Aí nem precisa do `if (text.length < 3) { ...`

2020-09-01 19:51 UTC, lauralucca commented on src/components/Avatar/Avatar.tsx
> +    .map(item => item[0]);
Eu prefiro usar `string.charAt(0)` em vez do `string[0]`, porque aí se a string for vazia não corre o risco de retornar `undefined`. Acho que do jeito que está não quebra, mas o seguro morreu de velho. haha

2020-09-01 21:08 UTC, lauralucca commented on src/components/Avatar/Avatar.stories.tsx
> +      text={text('Label', 'DS')}
Acho que fica legal colocar um nome grande no text, pra mostrar que funciona se passar um nome completo. Tipo "Natura Design System"

2020-09-01 21:15 UTC, lauralucca commented on src/common/themeSelectors/avatarSizes/avatarSizes.test.ts
> +  ));
No PR #71 a gente discutiu sobre usar `describe.each` em vez de `for.each` nos testes, queria saber o que você acha.
https://github.com/natura-cosmeticos/natds-rn/pull/71/files#diff-c96216ff452ffe4bdd5c04edf99a0acf

(eu achei mais conciso e gostei)

2020-09-03 16:32 UTC, arielwb requested changes

2020-09-03 16:32 UTC, arielwb commented on src/components/Avatar/Avatar.tsx
> +export type AvatarTypes = 'image' | 'letter' | 'anonymous' | string;
seria melhor remover o tipo `string` do final desses tipos, para restringir os tipos somente ao que estamos preparados para aceitar

2020-09-03 16:32 UTC, arielwb commented on src/components/Avatar/Avatar.tsx
> +      theme={theme} /> }
nao precisamos repetir o componente AvatarImage, porque so trocamos o `source`.
A sugestão abaixo também faz com que o avatar `anonymous` seja o default (se type='banana') o que na solução atual renderiza uma view vazia.

```
{
          type === 'letter'
            ? (
              <AvatarLetter
                accessibilityLabel={accessibilityLabel}
                accessibilityHint={accessibilityHint}
                accessibilityRole="text"
                size={size}
                theme={theme}
                testID={testID}
                type={type}
              >
                {getTextValue(text)}
              </AvatarLetter>
            )
            : (
              <AvatarImage
                accessibilityLabel={accessibilityLabel}
                accessibilityHint={accessibilityHint}
                testID={testID}
                type={type}
                source={type === 'image' ? imgSource : IconAnonymous}
                size={size}
                theme={theme}
              />
            )
        }
```

2020-09-03 21:08 UTC, douglasofreitas commented on src/components/Avatar/Avatar.stories.tsx
> +const imgSource = 'https://pbs.twimg.com/profile_images/1285932878795333632/Wl95KE_m_400x400.jpg';
no DS do Web eu também não vi imagem. pode ser o storybook

2020-09-03 21:08 UTC, douglasofreitas commented on src/components/Avatar/Avatar.tsx
> +  const firstAndLast = `${firstLetters[0]}${firstLetters[firstLetters.length - 1]}`;
mudei o algoritmo para arrumar alguns casos

2020-09-06 15:10 UTC, jimmyandrade commented on src/components/Avatar/Avatar.stories.tsx
> +const imgSource = 'https://pbs.twimg.com/profile_images/1285932878795333632/Wl95KE_m_400x400.jpg';
@lauralucca confesso que não sei te responder sobre :(

2020-09-08 14:06 UTC, lauralucca commented
Acho que tá faltando adicionar o avatar em `src/components/index.ts`

2020-09-08 14:23 UTC, lauralucca commented on src/components/Avatar/Avatar.tsx
> +  return `${firstLetters.charAt(0)}${firstLetters.charAt(firstLetters.length - 1)}`;
faz sentido pra gente ele pegar a primeira e última letra se vier um nome só?

![image](https://user-images.githubusercontent.com/30187869/92488957-96424c00-f1c5-11ea-8538-de303edc042c.png)

2020-09-09 12:10 UTC, douglasofreitas commented on src/components/Avatar/Avatar.tsx
> +  return `${firstLetters.charAt(0)}${firstLetters.charAt(firstLetters.length - 1)}`;
fiz o ajuste do algoritimo. agora só pega a primeira letra de cada palavra. e havendo mais de duas palavras, apenas a primeira  e a última

2020-09-17 18:11 UTC, merged

2020-09-25 20:26 UTC, jimmyandrade reviewed
Apenas um typo que poderia ser corrigido

2020-09-25 20:26 UTC, jimmyandrade commented on src/components/Avatar/Avatar.tsx
> +  const textFormated = text.trim().toUpperCase();
Tem um typo aqui: `textFormatted` deveria ser com 2 Ts

2020-09-25 20:26 UTC, jimmyandrade commented on ios/Podfile.lock
> +COCOAPODS: 1.9.1
Dúvida: por que fizemos downgrade da versão do cocoapods?